"""Create users table

Revision ID: 28125b04919a
Revises: 
Create Date: 2025-12-13 02:12:54.274768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28125b04919a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='ユーザーID（UUID）'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='ユーザー名'),
    sa.Column('role', sa.Enum('OWNER', 'TEAM', 'CLIENT_PREMIUM_PLUS', 'CLIENT_PREMIUM', 'CLIENT_BASIC', name='userrole'), nullable=False, comment='ロール'),
    sa.Column('google_id', sa.String(length=255), nullable=True, comment='Google OAuth ID'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='アバター画像URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
