"""add clients, categories, tags tables

Revision ID: 3feb5fddb768
Revises: 28125b04919a
Create Date: 2025-12-13 02:27:50.831683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3feb5fddb768'
down_revision: Union[str, None] = '28125b04919a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False, comment='カテゴリID（UUID）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='カテゴリ名'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False, comment='タグID（UUID）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='タグ名'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False, comment='クライアントID（UUID）'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ユーザーID（外部キー）'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='会社名'),
    sa.Column('plan', sa.Enum('BASIC', 'PREMIUM', 'PREMIUM_PLUS', name='clientplan'), nullable=False, comment='契約プラン'),
    sa.Column('knowledge_count', sa.Integer(), nullable=False, comment='ナレッジ数'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
