"""add_projects_videos_workflow_steps_tables

Revision ID: 437c169ca105
Revises: 3feb5fddb768
Create Date: 2025-12-13 02:48:58.780450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '437c169ca105'
down_revision: Union[str, None] = '3feb5fddb768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # knowledgesテーブルはスライス3-Aで作成済みのためスキップ
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False, comment='プロジェクトID（UUID）'),
    sa.Column('client_id', sa.UUID(), nullable=False, comment='クライアントID（外部キー）'),
    sa.Column('knowledge_id', sa.UUID(), nullable=True, comment='ナレッジID（外部キー）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='プロジェクト名'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明'),
    sa.Column('status', sa.Enum('PLANNING', 'PRODUCTION', 'SCHEDULED', 'PUBLISHED', 'CANCELLED', name='projectstatus'), nullable=False, comment='ステータス'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_knowledge_id'), 'projects', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    # chat_sessionsテーブルはスライス3-Aで作成済みのためスキップ
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False, comment='動画ID（UUID）'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='プロジェクトID（外部キー）'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='タイトル'),
    sa.Column('script', sa.Text(), nullable=True, comment='台本'),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PRODUCTION', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED', 'REJECTED', name='videostatus'), nullable=False, comment='ステータス'),
    sa.Column('youtube_url', sa.String(length=500), nullable=True, comment='YouTube URL'),
    sa.Column('analytics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分析データ（JSON）'),
    sa.Column('video_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='メタデータ（説明文、タグ等）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_project_id'), 'videos', ['project_id'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False, comment='ワークフローステップID（UUID）'),
    sa.Column('video_id', sa.UUID(), nullable=False, comment='動画ID（外部キー）'),
    sa.Column('step_name', sa.Enum('RESEARCH', 'PLANNING', 'SCRIPT', 'METADATA', 'AUDIO', 'AVATAR', 'EDITING', 'PUBLISH', name='workflowstepname'), nullable=False, comment='ステップ名'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='workflowstepstatus'), nullable=False, comment='ステータス'),
    sa.Column('approver_id', sa.UUID(), nullable=True, comment='承認者ID（外部キー）'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='承認日時'),
    sa.Column('comments', sa.Text(), nullable=True, comment='コメント・修正依頼'),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='実行結果データ（JSON）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_video_id'), 'workflow_steps', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_steps_video_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_project_id'), table_name='videos')
    op.drop_table('videos')
    # chat_sessionsとknowledgesはスライス3-Aで管理されるためスキップ
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_knowledge_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
