"""Add research table

Revision ID: 670db495bfb6
Revises: 437c169ca105
Create Date: 2025-12-13 07:28:49.416009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670db495bfb6'
down_revision: Union[str, None] = '437c169ca105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_type', sa.Enum('COMPETITOR_CHANNEL', 'POPULAR_VIDEO', 'KEYWORD_TREND', 'NEWS_TREND', name='researchtype'), nullable=False, comment='リサーチタイプ'),
    sa.Column('query', sa.String(length=500), nullable=False, comment='検索クエリ'),
    sa.Column('data', sa.JSON(), nullable=False, comment='取得データ（JSON）'),
    sa.Column('cache_expires_at', sa.DateTime(), nullable=False, comment='キャッシュ有効期限'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_query'), 'research', ['query'], unique=False)
    op.create_index(op.f('ix_research_research_type'), 'research', ['research_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_research_type'), table_name='research')
    op.drop_index(op.f('ix_research_query'), table_name='research')
    op.drop_table('research')
    # ### end Alembic commands ###
