"""add_content_compound_tables

Revision ID: 88d468032377
Revises: bba4ec8c21ad
Create Date: 2025-12-18 00:26:27.180414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88d468032377'
down_revision: Union[str, None] = 'bba4ec8c21ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='動画IDリスト'),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('avg_retention', sa.Float(), nullable=False, comment='平均視聴維持率（%）'),
    sa.Column('cluster_score', sa.Float(), nullable=False, comment='クラスター全体の評価スコア'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_clusters_knowledge_id'), 'content_clusters', ['knowledge_id'], unique=False)
    op.create_table('compound_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('referral_views', sa.Integer(), nullable=False, comment='他動画からの流入視聴数'),
    sa.Column('referral_watch_time', sa.Float(), nullable=False, comment='流入視聴時間（分）'),
    sa.Column('outbound_clicks', sa.Integer(), nullable=False, comment='他動画への誘導クリック数'),
    sa.Column('compound_score', sa.Float(), nullable=False, comment='複利スコア（0-100）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compound_metrics_date'), 'compound_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_compound_metrics_video_id'), 'compound_metrics', ['video_id'], unique=False)
    op.create_table('content_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_video_id', sa.UUID(), nullable=False),
    sa.Column('target_video_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.Enum('END_SCREEN', 'CARD', 'DESCRIPTION', 'PINNED_COMMENT', name='linktype'), nullable=False),
    sa.Column('position_seconds', sa.Integer(), nullable=True, comment='挿入位置（秒）'),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False, comment='クリック率'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_links_source_video_id'), 'content_links', ['source_video_id'], unique=False)
    op.create_index(op.f('ix_content_links_target_video_id'), 'content_links', ['target_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_links_target_video_id'), table_name='content_links')
    op.drop_index(op.f('ix_content_links_source_video_id'), table_name='content_links')
    op.drop_table('content_links')
    op.drop_index(op.f('ix_compound_metrics_video_id'), table_name='compound_metrics')
    op.drop_index(op.f('ix_compound_metrics_date'), table_name='compound_metrics')
    op.drop_table('compound_metrics')
    op.drop_index(op.f('ix_content_clusters_knowledge_id'), table_name='content_clusters')
    op.drop_table('content_clusters')
    # ### end Alembic commands ###
