/**
 * Research Service - Mock Data
 *
 * 開発・テスト用モックデータ
 */
import type {
  Competitor,
  PopularVideo,
  TrendKeyword,
  TrendNews,
  BookRanking,
} from '../../types';

export const mockCompetitors: Competitor[] = [
  {
    id: 'mock-1',
    channelId: 'UC_x5XG1OV2P6uZZ5FSM9Ttw',
    name: 'Google Developers',
    thumbnailUrl: 'https://via.placeholder.com/80',
    subscriberCount: 2340000,
    videoCount: 1250,
    avgViews: 45000,
    growthRate: 2.3,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'mock-2',
    channelId: 'UCVHFbqXqoYvEWM1Ddxl0QDg',
    name: 'テックチャンネル',
    thumbnailUrl: 'https://via.placeholder.com/80',
    subscriberCount: 156000,
    videoCount: 320,
    avgViews: 12500,
    growthRate: 5.8,
    createdAt: '2023-06-10T00:00:00Z',
  },
  {
    id: 'mock-3',
    channelId: 'UCabcdefghijk',
    name: 'ビジネスマスター',
    thumbnailUrl: 'https://via.placeholder.com/80',
    subscriberCount: 89000,
    videoCount: 180,
    avgViews: 8200,
    growthRate: 3.1,
    createdAt: '2023-09-22T00:00:00Z',
  },
];

export const mockPopularVideos: PopularVideo[] = [
  {
    id: 'video-1',
    videoId: 'abc123',
    title: '【完全解説】初心者向けプログラミング入門',
    views: 1250000,
    channelName: 'テックチャンネル',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-11-15T00:00:00Z',
  },
  {
    id: 'video-2',
    videoId: 'def456',
    title: 'ビジネス成功の秘訣TOP10',
    views: 980000,
    channelName: 'ビジネスマスター',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-11-20T00:00:00Z',
  },
  {
    id: 'video-3',
    videoId: 'ghi789',
    title: 'AI活用で業務効率化する方法',
    views: 850000,
    channelName: 'テックチャンネル',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-11-10T00:00:00Z',
  },
  {
    id: 'video-4',
    videoId: 'jkl012',
    title: 'マーケティング戦略の基礎',
    views: 720000,
    channelName: 'ビジネスマスター',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-11-05T00:00:00Z',
  },
  {
    id: 'video-5',
    videoId: 'mno345',
    title: 'Web開発トレンド2024',
    views: 650000,
    channelName: 'テックチャンネル',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-10-28T00:00:00Z',
  },
  {
    id: 'video-6',
    videoId: 'pqr678',
    title: 'データ分析で売上アップ',
    views: 580000,
    channelName: 'ビジネスマスター',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-10-22T00:00:00Z',
  },
  {
    id: 'video-7',
    videoId: 'stu901',
    title: 'クラウド技術完全ガイド',
    views: 520000,
    channelName: 'テックチャンネル',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-10-15T00:00:00Z',
  },
  {
    id: 'video-8',
    videoId: 'vwx234',
    title: 'リーダーシップの極意',
    views: 480000,
    channelName: 'ビジネスマスター',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-10-08T00:00:00Z',
  },
  {
    id: 'video-9',
    videoId: 'yza567',
    title: 'セキュリティ対策の最前線',
    views: 420000,
    channelName: 'テックチャンネル',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-10-01T00:00:00Z',
  },
  {
    id: 'video-10',
    videoId: 'bcd890',
    title: 'チームマネジメント実践',
    views: 380000,
    channelName: 'ビジネスマスター',
    thumbnailUrl: 'https://via.placeholder.com/120x68',
    publishedAt: '2024-09-24T00:00:00Z',
  },
];

export const mockTrendKeywords: TrendKeyword[] = [
  {
    id: 'keyword-1',
    keyword: 'AI マーケティング',
    growthRate: 150,
    searchVolume: 98000,
    category: 'ビジネス',
    isFire: true,
  },
  {
    id: 'keyword-2',
    keyword: 'YouTube SEO 2025',
    growthRate: 120,
    searchVolume: 76000,
    category: 'マーケティング',
    isFire: true,
  },
  {
    id: 'keyword-3',
    keyword: 'リモートワーク ツール',
    growthRate: 95,
    searchVolume: 65000,
    category: 'ビジネス',
    isFire: true,
  },
  {
    id: 'keyword-4',
    keyword: 'データ分析 入門',
    growthRate: 80,
    searchVolume: 54000,
    category: 'テクノロジー',
    isFire: true,
  },
];

export const mockTrendNews: TrendNews[] = [
  {
    id: 'news-1',
    title: 'AI技術の最新トレンド2025年版が発表',
    description: '大手テック企業が発表した最新のAI技術動向についてのレポート...',
    source: 'TechCrunch',
    url: 'https://example.com/news1',
    thumbnailUrl: 'https://via.placeholder.com/100',
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-2',
    title: 'マーケティング自動化ツールが急成長',
    description: '中小企業向けのマーケティング自動化プラットフォームが注目を集める...',
    source: 'MarketingLand',
    url: 'https://example.com/news2',
    thumbnailUrl: 'https://via.placeholder.com/100',
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-3',
    title: 'リモートワークツールの新機能が話題に',
    description: 'チームコラボレーションを促進する新しい機能がリリース...',
    source: 'The Verge',
    url: 'https://example.com/news3',
    thumbnailUrl: 'https://via.placeholder.com/100',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockBookRankings: BookRanking[] = [
  {
    id: 'book-1',
    title: 'マーケティングの新常識',
    rating: 4.5,
    reviewCount: 1250,
    category: 'ビジネス・マーケティング',
    imageUrl: 'https://via.placeholder.com/60x90',
    rank: 1,
  },
  {
    id: 'book-2',
    title: 'AIビジネス活用大全',
    rating: 4.3,
    reviewCount: 980,
    category: 'ビジネス・マーケティング',
    imageUrl: 'https://via.placeholder.com/60x90',
    rank: 2,
  },
  {
    id: 'book-3',
    title: 'データドリブン経営の教科書',
    rating: 4.7,
    reviewCount: 1580,
    category: 'ビジネス・マーケティング',
    imageUrl: 'https://via.placeholder.com/60x90',
    rank: 3,
  },
  {
    id: 'book-4',
    title: 'YouTubeで売上を10倍にする方法',
    rating: 4.2,
    reviewCount: 720,
    category: 'ビジネス・マーケティング',
    imageUrl: 'https://via.placeholder.com/60x90',
    rank: 4,
  },
  {
    id: 'book-5',
    title: 'コンテンツマーケティング実践講座',
    rating: 4.6,
    reviewCount: 1100,
    category: 'ビジネス・マーケティング',
    imageUrl: 'https://via.placeholder.com/60x90',
    rank: 5,
  },
];
